# node docker compose file template

version: '3.8'
services:
  node:
    image: hyperledger/besu:latest
    container_name: node-3
    volumes:
      - ./data:/data
      - ../genesis.json:/genesis.json
    ports:
      - "30305:30305" # Replace with actual port
      - "8550:8550" # Replace with actual port
      - "8549:8549" # Replace with actual port
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=enode://56ef917d413a66b2a56849f3c3827a0b34454c5e0fb61cc325815afacf5860581190331c598365dda51803d38a8119132b7492c0d3c29c7b8e34b49bd2cdf8b9@192.168.1.100:30303 # Replace with bootnode's enode URL
      - --p2p-port=30305 # Replace with actual port
      - --p2p-host=0.0.0.0
      - --rpc-http-enabled
      - --rpc-ws-enabled
      - --rpc-http-port=8550
      - --rpc-http-host=0.0.0.0
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8549
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist="*"
      - --rpc-http-cors-origins="all" 
    networks:
      besu-network:
        ipv4_address: 192.168.1.102

networks:
  besu-network:
    external: true
