# node docker compose file template

version: '3.8'
services:
  node:
    image: hyperledger/besu:latest
    container_name: node-2
    volumes:
      - ./data:/data
      - ../genesis.json:/genesis.json
    ports:
      - "30304:30304" # Replace with actual port
      - "8548:8548" # Replace with actual port
      - "8547:8547" # Replace with actual port
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=enode://24e4589abd04821b8183e98509e57215956aa6b5959c2027c26922df4c182b654b15c777ce1a1c8ca6b928447ba5cabd23639706295ae5015cd62ec4c1a80b3a@192.168.1.100:30303 # Replace with bootnode's enode URL
      - --p2p-port=30304 # Replace with actual port
      - --p2p-host=0.0.0.0
      - --rpc-http-enabled
      - --rpc-ws-enabled
      - --rpc-http-port=8548
      - --rpc-http-host=0.0.0.0
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8547
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist="*"
      - --rpc-http-cors-origins="all" 
    networks:
      besu-network:
        ipv4_address: 192.168.1.101

networks:
  besu-network:
    external: true
