# node docker compose file template
services:
  node:
    image: hyperledger/besu:24.10.0
    container_name: NET_ID-NODE_INDEX
    volumes:
      - ./data:/data
      - ../genesis.json:/genesis.json
      - ./Tessera:/Tessera
      - ./Tessera/data:/Tessera/data
    ports:
      - "P2P_PORT:P2P_PORT" # Replace with actual port
      - "RPC_HTTP_PORT:RPC_HTTP_PORT" # Replace with actual port
      - "RPC_WS_PORT:RPC_WS_PORT" # Replace with actual port
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=ENODE_URL # Replace with bootnode's enode URL
      - --p2p-port=P2P_PORT # Replace with actual port
      - --p2p-host=P2P_HOST
      - --rpc-http-enabled
      - --rpc-ws-enabled
      - --rpc-http-port=RPC_HTTP_PORT
      - --rpc-http-host=HTTP_HOST
      - --rpc-ws-host=WS_HOST
      - --rpc-ws-port=RPC_WS_PORT
      - --rpc-http-api=ETH,NET,WEB3,TRACE,DEBUG,ADMIN
      - --host-allowlist="*"
      - --rpc-http-cors-origins="all"
      - --privacy-enabled
      - --privacy-url=http://tessera-NODE_INDEX:TESS_THIRD_PARTY_PORT
      - --privacy-public-key-file=/Tessera/data/nodeKey.pub
      - --profile=ENTERPRISE
    depends_on:
      - tessera
    networks:
      NET_ID:
        ipv4_address: NODE_IP

  tessera:
    image: quorumengineering/tessera:latest
    container_name: tessera-NODE_INDEX
    volumes:
      - ./Tessera:/Tessera
      - ./Tessera/data:/Tessera/data
    ports:
      - "TESS_THIRD_PARTY_PORT:TESS_THIRD_PARTY_PORT" # ThirdParty service
      - "TESS_Q2T_PORT:TESS_Q2T_PORT" # Q2T service
      - "TESS_P2P:TESS_P2P" # P2P service
      - "TESS_HEALTH_PORT:TESS_HEALTH_PORT" # Optional admin/health port
    command: [ "-configfile", "/Tessera/tessera.conf" ]
    networks:
      NET_ID:
        ipv4_address: TESSERA_IP

networks:
  NET_ID:
    external: true
